# Natural Language Processing

https://blog.paperspace.com/pytorch-101-understanding-graphs-and-automatic-differentiation/

In [ ]:
- context
- intent

In [ ]:
- pytorch - deep learning framework
- nlp fundamental methods to understand text

# Bag of Words

<img src='n1.png' />


In [ ]:
bag of words representation

the cat sat on the mat  -> [2,1,0,1,1,1]
the dog sat on the cat

# Sequential Representation

<img src='n2.png' />

# PyTorch 

In [ ]:
- it have tensors(data structure) with hardware accelerations (GPUs)
- dynamic computational graphs(data structures)

In [ ]:
int -> 2 bytes (16 bits)

int a = 10;

float a = 10.65; -> 4 bytes(32 bits)


Neural Network
- forward pass 
- backward pass

A-> B
|
C-> X

# Tensors

<img src='n3.png' />

<img src='Tensors.png' />

In [1]:
import torch

In [2]:
x = torch.tensor([1,2])

print(x)

tensor([1, 2])


In [3]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

print(x * y)

tensor([3, 8])


In [4]:
x = torch.tensor([[1,2], [5,3], [0,4]])

print(x)

tensor([[1, 2],
        [5, 3],
        [0, 4]])


In [6]:
print(x[0][1])

tensor(2)


In [7]:
print(x[0][1].item())

2


In [8]:
print(x.shape)

torch.Size([3, 2])


# Neural Network in PyTorch

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train.csv')
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
# 28x28 -> 784 pixels

In [3]:
from torch import nn, optim
import torch.nn.functional as F
import torch.utils.data as data
import torch
from torch.autograd import Variable

In [4]:
# plt.imshow(np.reshape(df.values[0][1:], (28,28)))
# plt.show()

In [5]:
train = pd.read_csv('train.csv')
train_labels = train['label'].values
train = train.drop('label', axis=1).values.reshape(len(train), 1,28,28)

In [6]:
x = torch.Tensor(train.astype(float))
y = torch.Tensor(train_labels).long()

In [7]:
# build the classifier

class MNISTClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 392)
        self.fc2 = nn.Linear(392, 196)
        self.fc3 = nn.Linear(196, 98)
        self.fc4 = nn.Linear(98, 10)
        
        self.dropout = nn.Dropout(p=0.2)
    
    def forward(self, x):
        x = x.view(x.shape[0], -1)                 # doubt
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.dropout(F.relu(self.fc2(x)))
        x = self.dropout(F.relu(self.fc3(x)))
        x = F.log_softmax(self.fc4(x), dim=1)
        
        return x

In [8]:
model = MNISTClassifier()

loss_function = nn.NLLLoss()
opt = optim.Adam(model.parameters(), lr=0.001)

In [9]:
for epoch in range(50):
    images = Variable(x)
    labels = Variable(y)
    
    opt.zero_grad()
    outputs = model(images)
    
    loss = loss_function(outputs, labels)
    loss.backward()
    opt.step()
    print("Epoch [%d/%d] Loss: %.4f" %(epoch + 1, 50, loss.data.item()))

Epoch [1/50] Loss: 6.6796
Epoch [2/50] Loss: 3.9992
Epoch [3/50] Loss: 2.6990
Epoch [4/50] Loss: 2.0911
Epoch [5/50] Loss: 1.7405
Epoch [6/50] Loss: 1.5250
Epoch [7/50] Loss: 1.3482
Epoch [8/50] Loss: 1.1700
Epoch [9/50] Loss: 1.0369
Epoch [10/50] Loss: 0.9857
Epoch [11/50] Loss: 0.8652
Epoch [12/50] Loss: 0.8285
Epoch [13/50] Loss: 0.7171
Epoch [14/50] Loss: 0.6951
Epoch [15/50] Loss: 0.6145
Epoch [16/50] Loss: 0.5979
Epoch [17/50] Loss: 0.5718
Epoch [18/50] Loss: 0.4982
Epoch [19/50] Loss: 0.5055
Epoch [20/50] Loss: 0.4541
Epoch [21/50] Loss: 0.4331
Epoch [22/50] Loss: 0.3708
Epoch [23/50] Loss: 0.3491
Epoch [24/50] Loss: 0.3527
Epoch [25/50] Loss: 0.3309
Epoch [26/50] Loss: 0.2788
Epoch [27/50] Loss: 0.2816
Epoch [28/50] Loss: 0.2198
Epoch [29/50] Loss: 0.2277
Epoch [30/50] Loss: 0.2406
Epoch [31/50] Loss: 0.1987
Epoch [32/50] Loss: 0.1832
Epoch [33/50] Loss: 0.1685
Epoch [34/50] Loss: 0.1633
Epoch [35/50] Loss: 0.1420
Epoch [36/50] Loss: 0.1355
Epoch [37/50] Loss: 0.1276
Epoch [38/

In [10]:
test = pd.read_csv('test.csv')
test_labels = test['label'].values
test = test.drop('label', axis=1).values.reshape(len(test), 1,28,28)

In [11]:
xtest = torch.Tensor(train.astype(float))
ytest = torch.Tensor(train_labels).long()

In [12]:
preds = model(xtest)

In [14]:
print(preds[0])

tensor([-19.8444,  -0.0893,  -8.2741, -11.2113, -11.4445,  -6.5766, -14.6546,
         -5.5649,  -2.5265, -12.1194], grad_fn=<SelectBackward0>)


In [15]:
_, predictionlabel = torch.max(preds.data, 1)
predictionlabel = predictionlabel.tolist()

predictionlabel = pd.Series(predictionlabel)
test_labels = pd.Series(test_labels)

pred_table = pd.concat([predictionlabel, test_labels], axis=1)
pred_table.columns = ['Predicted value', 'True Value']

pred_table.head()

Predicted value  True Value
0                1         9.0
1                0         5.0
2                1         2.0
3                4         4.0
4                0         1.0

# Word Embeddings

<img src='n2.png' />

In [ ]:
word into numerical representation(one-hot encoding)

- semantic relationship

cat == cat

cat <==> dog

# Global Vector for Word Embeddings

https://nlp.stanford.edu/projects/glove/

In [16]:
def loadGlove(path):
    file = open(path, 'r', encoding='utf8')
    model = {}
    
    for l in file:
        line = l.split()
        word = line[0]
        value = np.array([float(val) for val in line[1:]])
        model[word] = value
    
    return model

glove = loadGlove('glove.6B.50d.txt')

In [17]:
glove['python']   # vector embedding for the word Python

array([ 0.5897  , -0.55043 , -1.0106  ,  0.41226 ,  0.57348 ,  0.23464 ,
       -0.35773 , -1.78    ,  0.10745 ,  0.74913 ,  0.45013 ,  1.0351  ,
        0.48348 ,  0.47954 ,  0.51908 , -0.15053 ,  0.32474 ,  1.0789  ,
       -0.90894 ,  0.42943 , -0.56388 ,  0.69961 ,  0.13501 ,  0.16557 ,
       -0.063592,  0.35435 ,  0.42819 ,  0.1536  , -0.47018 , -1.0935  ,
        1.361   , -0.80821 , -0.674   ,  1.2606  ,  0.29554 ,  1.0835  ,
        0.2444  , -1.1877  , -0.60203 , -0.068315,  0.66256 ,  0.45336 ,
       -1.0178  ,  0.68267 , -0.20788 , -0.73393 ,  1.2597  ,  0.15425 ,
       -0.93256 , -0.15025 ])

## How the system know that these words are similar?

Cosine Similarity

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
cosine_similarity(glove['cat'].reshape(1,-1), glove['dog'].reshape(1,-1))

array([[0.92180053]])

In [20]:
cosine_similarity(glove['cat'].reshape(1,-1), glove['piano'].reshape(1,-1))

array([[0.19825255]])

In [23]:
cosine_similarity(glove['king'].reshape(1,-1), glove['queen'].reshape(1,-1))

array([[0.7839043]])

# n-gram

In [ ]:
the cat sat on the dog
the dog sat on the cat


bag of words representation of the above sentences are identical


In [ ]:
bi-gram
        - the cat, the dog, cat sat, dog sat, sat on, on the
1       -    1       1          1       0      1         1
2       -    1       1          0       1      1         1

n-grams

# Tokenization

In [24]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

In [25]:
text = 'this is a single sentence.'

tokens = word_tokenize(text)

print(tokens)

['this', 'is', 'a', 'single', 'sentence', '.']


In [26]:
no_punctuation = [word.lower() for word in tokens if word.isalpha()]
no_punctuation

['this', 'is', 'a', 'single', 'sentence']

In [27]:
text = 'this is the first sentence. this is the second sentence. this is the document.'

print(sent_tokenize(text))

['this is the first sentence.', 'this is the second sentence.', 'this is the document.']


In [28]:
print([word_tokenize(sentence) for sentence in sent_tokenize(text)])

[['this', 'is', 'the', 'first', 'sentence', '.'], ['this', 'is', 'the', 'second', 'sentence', '.'], ['this', 'is', 'the', 'document', '.']]


In [29]:
stop_words = stopwords.words('english')

print(stop_words[:20])

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']


In [30]:
text = 'this is the first sentence. this is the second sentence. this is the document.'

tokens = [token for token in word_tokenize(text) if token not in stop_words]

print(tokens)

['first', 'sentence', '.', 'second', 'sentence', '.', 'document', '.']


# POS(Parts Of Speech) tagging and chunking

In [ ]:
the big dog is sleeping on the bed.


In [38]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [WinError 10060] A connection attempt failed because
[nltk_data]     the connected party did not properly respond after a
[nltk_data]     period of time, or established connection failed
[nltk_data]     because connected host has failed to respond>


False

In [39]:
from nltk.tag import pos_tag

In [41]:
# text = "the big dog is sleeping on the bed."

# token = word_tokenize(text)

# print(pos_tag(token))

# error in the code

In [ ]:
nltk.help.upenn_tagset('VBG')

# TF-IDF

Term Frequency - Inverse Document Frequency


In [ ]:
this is a small giraffe
                   |
                weight to rare words